-- Run this script in the Supabase SQL Editor to create the necessary tables

-- Drop tables if they exist to start fresh (optional, be careful)
-- DROP TABLE IF EXISTS inactive_students;
-- DROP TABLE IF EXISTS absent_students;
-- DROP TABLE IF EXISTS fees;
-- DROP TABLE IF EXISTS students;
-- DROP TABLE IF EXISTS settings;
-- DROP TABLE IF EXISTS users;

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text,
  email text unique,
  phone_number text,
  password text not null,
  pin text default '1234'
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  "firstName" text not null,
  "lastName" text not null,
  "phoneNumber" text,
  gender text,
  "fatherName" text,
  address text,
  status text default 'active',
  "beltColor" text default 'white',
  attendance jsonb default '{}'::jsonb
);

create table if not exists fees (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  student_name text,
  amount decimal(10,2) not null,
  month text not null,
  year int not null,
  payment_date date not null,
  payment_method text default 'cash',
  notes text,
  user_id bigint references users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique (student_id, month, year)
);

create table if not exists absent_students (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  student_name text,
  phone_number text,
  absent_date date,
  reason text,
  user_id bigint references users(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists "settings" (
  key text primary key,
  value text not null
);

create table if not exists inactive_students (
  id bigint generated by default as identity primary key,
  original_id bigint,
  "firstName" text not null,
  "lastName" text not null,
  "phoneNumber" text,
  gender text,
  "fatherName" text,
  address text,
  "beltColor" text default 'white',
  attendance jsonb,
  user_id bigint references users(id),
  moved_date timestamp with time zone default timezone('utc'::text, now())
);

-- Insert default admin user if not exists
INSERT INTO users (username, email, password, pin)
VALUES ('admin', 'admin@attendance.local', 'admin123', '1234')
ON CONFLICT (email) DO NOTHING;
